// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BizEventProtoc.proto

package com.java.core.redis.protobuf;

public final class BizEventProtoc {
  private BizEventProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BizEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.java.core.redis.protobuf.BizEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string date = 2;</code>
     */
    String getDate();
    /**
     * <code>string date = 2;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>string name = 3;</code>
     */
    String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string title = 4;</code>
     */
    String getTitle();
    /**
     * <code>string title = 4;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>int32 type = 5;</code>
     */
    int getType();

    /**
     * <code>string team = 6;</code>
     */
    String getTeam();
    /**
     * <code>string team = 6;</code>
     */
    com.google.protobuf.ByteString
        getTeamBytes();

    /**
     * <code>string imageObj = 7;</code>
     */
    String getImageObj();
    /**
     * <code>string imageObj = 7;</code>
     */
    com.google.protobuf.ByteString
        getImageObjBytes();

    /**
     * <code>string coverObj = 8;</code>
     */
    String getCoverObj();
    /**
     * <code>string coverObj = 8;</code>
     */
    com.google.protobuf.ByteString
        getCoverObjBytes();

    /**
     * <code>int32 direction = 9;</code>
     */
    int getDirection();

    /**
     * <code>string description = 10;</code>
     */
    String getDescription();
    /**
     * <code>string description = 10;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>int32 sequence = 11;</code>
     */
    int getSequence();

    /**
     * <code>int32 category = 12;</code>
     */
    int getCategory();

    /**
     * <code>string authorInfo = 13;</code>
     */
    String getAuthorInfo();
    /**
     * <code>string authorInfo = 13;</code>
     */
    com.google.protobuf.ByteString
        getAuthorInfoBytes();

    /**
     * <code>string url = 14;</code>
     */
    String getUrl();
    /**
     * <code>string url = 14;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>int32 listStatus = 15;</code>
     */
    int getListStatus();

    /**
     * <code>int32 instSearchStatus = 16;</code>
     */
    int getInstSearchStatus();

    /**
     * <code>int64 instId = 17;</code>
     */
    long getInstId();

    /**
     * <code>int32 hasAndroid = 18;</code>
     */
    int getHasAndroid();

    /**
     * <code>int32 hasIOS = 19;</code>
     */
    int getHasIOS();

    /**
     * <code>string androidVersion = 20;</code>
     */
    String getAndroidVersion();
    /**
     * <code>string androidVersion = 20;</code>
     */
    com.google.protobuf.ByteString
        getAndroidVersionBytes();

    /**
     * <code>string iosVersion = 21;</code>
     */
    String getIosVersion();
    /**
     * <code>string iosVersion = 21;</code>
     */
    com.google.protobuf.ByteString
        getIosVersionBytes();

    /**
     * <code>int32 platformType = 22;</code>
     */
    int getPlatformType();

    /**
     * <code>int32 coverType = 23;</code>
     */
    int getCoverType();

    /**
     * <code>string coverResourceList = 24;</code>
     */
    String getCoverResourceList();
    /**
     * <code>string coverResourceList = 24;</code>
     */
    com.google.protobuf.ByteString
        getCoverResourceListBytes();

    /**
     * <code>string detailResourceList = 25;</code>
     */
    String getDetailResourceList();
    /**
     * <code>string detailResourceList = 25;</code>
     */
    com.google.protobuf.ByteString
        getDetailResourceListBytes();

    /**
     * <code>string detailResourceIdArr = 26;</code>
     */
    String getDetailResourceIdArr();
    /**
     * <code>string detailResourceIdArr = 26;</code>
     */
    com.google.protobuf.ByteString
        getDetailResourceIdArrBytes();
  }
  /**
   * Protobuf type {@code com.java.core.redis.protobuf.BizEvent}
   */
  public  static final class BizEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.java.core.redis.protobuf.BizEvent)
      BizEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BizEvent.newBuilder() to construct.
    private BizEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BizEvent() {
      id_ = 0L;
      date_ = "";
      name_ = "";
      title_ = "";
      type_ = 0;
      team_ = "";
      imageObj_ = "";
      coverObj_ = "";
      direction_ = 0;
      description_ = "";
      sequence_ = 0;
      category_ = 0;
      authorInfo_ = "";
      url_ = "";
      listStatus_ = 0;
      instSearchStatus_ = 0;
      instId_ = 0L;
      hasAndroid_ = 0;
      hasIOS_ = 0;
      androidVersion_ = "";
      iosVersion_ = "";
      platformType_ = 0;
      coverType_ = 0;
      coverResourceList_ = "";
      detailResourceList_ = "";
      detailResourceIdArr_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BizEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 40: {

              type_ = input.readInt32();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              team_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              imageObj_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              coverObj_ = s;
              break;
            }
            case 72: {

              direction_ = input.readInt32();
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 88: {

              sequence_ = input.readInt32();
              break;
            }
            case 96: {

              category_ = input.readInt32();
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              authorInfo_ = s;
              break;
            }
            case 114: {
              String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 120: {

              listStatus_ = input.readInt32();
              break;
            }
            case 128: {

              instSearchStatus_ = input.readInt32();
              break;
            }
            case 136: {

              instId_ = input.readInt64();
              break;
            }
            case 144: {

              hasAndroid_ = input.readInt32();
              break;
            }
            case 152: {

              hasIOS_ = input.readInt32();
              break;
            }
            case 162: {
              String s = input.readStringRequireUtf8();

              androidVersion_ = s;
              break;
            }
            case 170: {
              String s = input.readStringRequireUtf8();

              iosVersion_ = s;
              break;
            }
            case 176: {

              platformType_ = input.readInt32();
              break;
            }
            case 184: {

              coverType_ = input.readInt32();
              break;
            }
            case 194: {
              String s = input.readStringRequireUtf8();

              coverResourceList_ = s;
              break;
            }
            case 202: {
              String s = input.readStringRequireUtf8();

              detailResourceList_ = s;
              break;
            }
            case 210: {
              String s = input.readStringRequireUtf8();

              detailResourceIdArr_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BizEventProtoc.internal_static_com_java_core_redis_protobuf_BizEvent_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BizEventProtoc.internal_static_com_java_core_redis_protobuf_BizEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BizEvent.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int DATE_FIELD_NUMBER = 2;
    private volatile Object date_;
    /**
     * <code>string date = 2;</code>
     */
    public String getDate() {
      Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 4;
    private volatile Object title_;
    /**
     * <code>string title = 4;</code>
     */
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>int32 type = 5;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int TEAM_FIELD_NUMBER = 6;
    private volatile Object team_;
    /**
     * <code>string team = 6;</code>
     */
    public String getTeam() {
      Object ref = team_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        team_ = s;
        return s;
      }
    }
    /**
     * <code>string team = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTeamBytes() {
      Object ref = team_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        team_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGEOBJ_FIELD_NUMBER = 7;
    private volatile Object imageObj_;
    /**
     * <code>string imageObj = 7;</code>
     */
    public String getImageObj() {
      Object ref = imageObj_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imageObj_ = s;
        return s;
      }
    }
    /**
     * <code>string imageObj = 7;</code>
     */
    public com.google.protobuf.ByteString
        getImageObjBytes() {
      Object ref = imageObj_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imageObj_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COVEROBJ_FIELD_NUMBER = 8;
    private volatile Object coverObj_;
    /**
     * <code>string coverObj = 8;</code>
     */
    public String getCoverObj() {
      Object ref = coverObj_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        coverObj_ = s;
        return s;
      }
    }
    /**
     * <code>string coverObj = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCoverObjBytes() {
      Object ref = coverObj_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        coverObj_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTION_FIELD_NUMBER = 9;
    private int direction_;
    /**
     * <code>int32 direction = 9;</code>
     */
    public int getDirection() {
      return direction_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 10;
    private volatile Object description_;
    /**
     * <code>string description = 10;</code>
     */
    public String getDescription() {
      Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 10;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQUENCE_FIELD_NUMBER = 11;
    private int sequence_;
    /**
     * <code>int32 sequence = 11;</code>
     */
    public int getSequence() {
      return sequence_;
    }

    public static final int CATEGORY_FIELD_NUMBER = 12;
    private int category_;
    /**
     * <code>int32 category = 12;</code>
     */
    public int getCategory() {
      return category_;
    }

    public static final int AUTHORINFO_FIELD_NUMBER = 13;
    private volatile Object authorInfo_;
    /**
     * <code>string authorInfo = 13;</code>
     */
    public String getAuthorInfo() {
      Object ref = authorInfo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        authorInfo_ = s;
        return s;
      }
    }
    /**
     * <code>string authorInfo = 13;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorInfoBytes() {
      Object ref = authorInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        authorInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 14;
    private volatile Object url_;
    /**
     * <code>string url = 14;</code>
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 14;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LISTSTATUS_FIELD_NUMBER = 15;
    private int listStatus_;
    /**
     * <code>int32 listStatus = 15;</code>
     */
    public int getListStatus() {
      return listStatus_;
    }

    public static final int INSTSEARCHSTATUS_FIELD_NUMBER = 16;
    private int instSearchStatus_;
    /**
     * <code>int32 instSearchStatus = 16;</code>
     */
    public int getInstSearchStatus() {
      return instSearchStatus_;
    }

    public static final int INSTID_FIELD_NUMBER = 17;
    private long instId_;
    /**
     * <code>int64 instId = 17;</code>
     */
    public long getInstId() {
      return instId_;
    }

    public static final int HASANDROID_FIELD_NUMBER = 18;
    private int hasAndroid_;
    /**
     * <code>int32 hasAndroid = 18;</code>
     */
    public int getHasAndroid() {
      return hasAndroid_;
    }

    public static final int HASIOS_FIELD_NUMBER = 19;
    private int hasIOS_;
    /**
     * <code>int32 hasIOS = 19;</code>
     */
    public int getHasIOS() {
      return hasIOS_;
    }

    public static final int ANDROIDVERSION_FIELD_NUMBER = 20;
    private volatile Object androidVersion_;
    /**
     * <code>string androidVersion = 20;</code>
     */
    public String getAndroidVersion() {
      Object ref = androidVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        androidVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string androidVersion = 20;</code>
     */
    public com.google.protobuf.ByteString
        getAndroidVersionBytes() {
      Object ref = androidVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        androidVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IOSVERSION_FIELD_NUMBER = 21;
    private volatile Object iosVersion_;
    /**
     * <code>string iosVersion = 21;</code>
     */
    public String getIosVersion() {
      Object ref = iosVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        iosVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string iosVersion = 21;</code>
     */
    public com.google.protobuf.ByteString
        getIosVersionBytes() {
      Object ref = iosVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        iosVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORMTYPE_FIELD_NUMBER = 22;
    private int platformType_;
    /**
     * <code>int32 platformType = 22;</code>
     */
    public int getPlatformType() {
      return platformType_;
    }

    public static final int COVERTYPE_FIELD_NUMBER = 23;
    private int coverType_;
    /**
     * <code>int32 coverType = 23;</code>
     */
    public int getCoverType() {
      return coverType_;
    }

    public static final int COVERRESOURCELIST_FIELD_NUMBER = 24;
    private volatile Object coverResourceList_;
    /**
     * <code>string coverResourceList = 24;</code>
     */
    public String getCoverResourceList() {
      Object ref = coverResourceList_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        coverResourceList_ = s;
        return s;
      }
    }
    /**
     * <code>string coverResourceList = 24;</code>
     */
    public com.google.protobuf.ByteString
        getCoverResourceListBytes() {
      Object ref = coverResourceList_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        coverResourceList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DETAILRESOURCELIST_FIELD_NUMBER = 25;
    private volatile Object detailResourceList_;
    /**
     * <code>string detailResourceList = 25;</code>
     */
    public String getDetailResourceList() {
      Object ref = detailResourceList_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        detailResourceList_ = s;
        return s;
      }
    }
    /**
     * <code>string detailResourceList = 25;</code>
     */
    public com.google.protobuf.ByteString
        getDetailResourceListBytes() {
      Object ref = detailResourceList_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        detailResourceList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DETAILRESOURCEIDARR_FIELD_NUMBER = 26;
    private volatile Object detailResourceIdArr_;
    /**
     * <code>string detailResourceIdArr = 26;</code>
     */
    public String getDetailResourceIdArr() {
      Object ref = detailResourceIdArr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        detailResourceIdArr_ = s;
        return s;
      }
    }
    /**
     * <code>string detailResourceIdArr = 26;</code>
     */
    public com.google.protobuf.ByteString
        getDetailResourceIdArrBytes() {
      Object ref = detailResourceIdArr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        detailResourceIdArr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, date_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, title_);
      }
      if (type_ != 0) {
        output.writeInt32(5, type_);
      }
      if (!getTeamBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, team_);
      }
      if (!getImageObjBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, imageObj_);
      }
      if (!getCoverObjBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, coverObj_);
      }
      if (direction_ != 0) {
        output.writeInt32(9, direction_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, description_);
      }
      if (sequence_ != 0) {
        output.writeInt32(11, sequence_);
      }
      if (category_ != 0) {
        output.writeInt32(12, category_);
      }
      if (!getAuthorInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, authorInfo_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, url_);
      }
      if (listStatus_ != 0) {
        output.writeInt32(15, listStatus_);
      }
      if (instSearchStatus_ != 0) {
        output.writeInt32(16, instSearchStatus_);
      }
      if (instId_ != 0L) {
        output.writeInt64(17, instId_);
      }
      if (hasAndroid_ != 0) {
        output.writeInt32(18, hasAndroid_);
      }
      if (hasIOS_ != 0) {
        output.writeInt32(19, hasIOS_);
      }
      if (!getAndroidVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 20, androidVersion_);
      }
      if (!getIosVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 21, iosVersion_);
      }
      if (platformType_ != 0) {
        output.writeInt32(22, platformType_);
      }
      if (coverType_ != 0) {
        output.writeInt32(23, coverType_);
      }
      if (!getCoverResourceListBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 24, coverResourceList_);
      }
      if (!getDetailResourceListBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 25, detailResourceList_);
      }
      if (!getDetailResourceIdArrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 26, detailResourceIdArr_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, date_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, title_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, type_);
      }
      if (!getTeamBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, team_);
      }
      if (!getImageObjBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, imageObj_);
      }
      if (!getCoverObjBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, coverObj_);
      }
      if (direction_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, direction_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, description_);
      }
      if (sequence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, sequence_);
      }
      if (category_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, category_);
      }
      if (!getAuthorInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, authorInfo_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, url_);
      }
      if (listStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, listStatus_);
      }
      if (instSearchStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, instSearchStatus_);
      }
      if (instId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(17, instId_);
      }
      if (hasAndroid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, hasAndroid_);
      }
      if (hasIOS_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, hasIOS_);
      }
      if (!getAndroidVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, androidVersion_);
      }
      if (!getIosVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(21, iosVersion_);
      }
      if (platformType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(22, platformType_);
      }
      if (coverType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(23, coverType_);
      }
      if (!getCoverResourceListBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(24, coverResourceList_);
      }
      if (!getDetailResourceListBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(25, detailResourceList_);
      }
      if (!getDetailResourceIdArrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(26, detailResourceIdArr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BizEvent)) {
        return super.equals(obj);
      }
      BizEvent other = (BizEvent) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getDate()
          .equals(other.getDate());
      result = result && getName()
          .equals(other.getName());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && (getType()
          == other.getType());
      result = result && getTeam()
          .equals(other.getTeam());
      result = result && getImageObj()
          .equals(other.getImageObj());
      result = result && getCoverObj()
          .equals(other.getCoverObj());
      result = result && (getDirection()
          == other.getDirection());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && (getSequence()
          == other.getSequence());
      result = result && (getCategory()
          == other.getCategory());
      result = result && getAuthorInfo()
          .equals(other.getAuthorInfo());
      result = result && getUrl()
          .equals(other.getUrl());
      result = result && (getListStatus()
          == other.getListStatus());
      result = result && (getInstSearchStatus()
          == other.getInstSearchStatus());
      result = result && (getInstId()
          == other.getInstId());
      result = result && (getHasAndroid()
          == other.getHasAndroid());
      result = result && (getHasIOS()
          == other.getHasIOS());
      result = result && getAndroidVersion()
          .equals(other.getAndroidVersion());
      result = result && getIosVersion()
          .equals(other.getIosVersion());
      result = result && (getPlatformType()
          == other.getPlatformType());
      result = result && (getCoverType()
          == other.getCoverType());
      result = result && getCoverResourceList()
          .equals(other.getCoverResourceList());
      result = result && getDetailResourceList()
          .equals(other.getDetailResourceList());
      result = result && getDetailResourceIdArr()
          .equals(other.getDetailResourceIdArr());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + TEAM_FIELD_NUMBER;
      hash = (53 * hash) + getTeam().hashCode();
      hash = (37 * hash) + IMAGEOBJ_FIELD_NUMBER;
      hash = (53 * hash) + getImageObj().hashCode();
      hash = (37 * hash) + COVEROBJ_FIELD_NUMBER;
      hash = (53 * hash) + getCoverObj().hashCode();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequence();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory();
      hash = (37 * hash) + AUTHORINFO_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorInfo().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + LISTSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getListStatus();
      hash = (37 * hash) + INSTSEARCHSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getInstSearchStatus();
      hash = (37 * hash) + INSTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInstId());
      hash = (37 * hash) + HASANDROID_FIELD_NUMBER;
      hash = (53 * hash) + getHasAndroid();
      hash = (37 * hash) + HASIOS_FIELD_NUMBER;
      hash = (53 * hash) + getHasIOS();
      hash = (37 * hash) + ANDROIDVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getAndroidVersion().hashCode();
      hash = (37 * hash) + IOSVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getIosVersion().hashCode();
      hash = (37 * hash) + PLATFORMTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPlatformType();
      hash = (37 * hash) + COVERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCoverType();
      hash = (37 * hash) + COVERRESOURCELIST_FIELD_NUMBER;
      hash = (53 * hash) + getCoverResourceList().hashCode();
      hash = (37 * hash) + DETAILRESOURCELIST_FIELD_NUMBER;
      hash = (53 * hash) + getDetailResourceList().hashCode();
      hash = (37 * hash) + DETAILRESOURCEIDARR_FIELD_NUMBER;
      hash = (53 * hash) + getDetailResourceIdArr().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BizEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BizEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BizEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BizEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BizEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BizEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BizEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BizEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BizEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BizEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BizEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BizEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BizEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.java.core.redis.protobuf.BizEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.java.core.redis.protobuf.BizEvent)
        BizEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BizEventProtoc.internal_static_com_java_core_redis_protobuf_BizEvent_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BizEventProtoc.internal_static_com_java_core_redis_protobuf_BizEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BizEvent.class, Builder.class);
      }

      // Construct using com.java.core.redis.protobuf.BizEventProtoc.BizEvent.newBuilder()
      public Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        date_ = "";

        name_ = "";

        title_ = "";

        type_ = 0;

        team_ = "";

        imageObj_ = "";

        coverObj_ = "";

        direction_ = 0;

        description_ = "";

        sequence_ = 0;

        category_ = 0;

        authorInfo_ = "";

        url_ = "";

        listStatus_ = 0;

        instSearchStatus_ = 0;

        instId_ = 0L;

        hasAndroid_ = 0;

        hasIOS_ = 0;

        androidVersion_ = "";

        iosVersion_ = "";

        platformType_ = 0;

        coverType_ = 0;

        coverResourceList_ = "";

        detailResourceList_ = "";

        detailResourceIdArr_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BizEventProtoc.internal_static_com_java_core_redis_protobuf_BizEvent_descriptor;
      }

      @Override
      public BizEvent getDefaultInstanceForType() {
        return BizEvent.getDefaultInstance();
      }

      @Override
      public BizEvent build() {
        BizEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BizEvent buildPartial() {
        BizEvent result = new BizEvent(this);
        result.id_ = id_;
        result.date_ = date_;
        result.name_ = name_;
        result.title_ = title_;
        result.type_ = type_;
        result.team_ = team_;
        result.imageObj_ = imageObj_;
        result.coverObj_ = coverObj_;
        result.direction_ = direction_;
        result.description_ = description_;
        result.sequence_ = sequence_;
        result.category_ = category_;
        result.authorInfo_ = authorInfo_;
        result.url_ = url_;
        result.listStatus_ = listStatus_;
        result.instSearchStatus_ = instSearchStatus_;
        result.instId_ = instId_;
        result.hasAndroid_ = hasAndroid_;
        result.hasIOS_ = hasIOS_;
        result.androidVersion_ = androidVersion_;
        result.iosVersion_ = iosVersion_;
        result.platformType_ = platformType_;
        result.coverType_ = coverType_;
        result.coverResourceList_ = coverResourceList_;
        result.detailResourceList_ = detailResourceList_;
        result.detailResourceIdArr_ = detailResourceIdArr_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BizEvent) {
          return mergeFrom((BizEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BizEvent other) {
        if (other == BizEvent.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getTeam().isEmpty()) {
          team_ = other.team_;
          onChanged();
        }
        if (!other.getImageObj().isEmpty()) {
          imageObj_ = other.imageObj_;
          onChanged();
        }
        if (!other.getCoverObj().isEmpty()) {
          coverObj_ = other.coverObj_;
          onChanged();
        }
        if (other.getDirection() != 0) {
          setDirection(other.getDirection());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getSequence() != 0) {
          setSequence(other.getSequence());
        }
        if (other.getCategory() != 0) {
          setCategory(other.getCategory());
        }
        if (!other.getAuthorInfo().isEmpty()) {
          authorInfo_ = other.authorInfo_;
          onChanged();
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (other.getListStatus() != 0) {
          setListStatus(other.getListStatus());
        }
        if (other.getInstSearchStatus() != 0) {
          setInstSearchStatus(other.getInstSearchStatus());
        }
        if (other.getInstId() != 0L) {
          setInstId(other.getInstId());
        }
        if (other.getHasAndroid() != 0) {
          setHasAndroid(other.getHasAndroid());
        }
        if (other.getHasIOS() != 0) {
          setHasIOS(other.getHasIOS());
        }
        if (!other.getAndroidVersion().isEmpty()) {
          androidVersion_ = other.androidVersion_;
          onChanged();
        }
        if (!other.getIosVersion().isEmpty()) {
          iosVersion_ = other.iosVersion_;
          onChanged();
        }
        if (other.getPlatformType() != 0) {
          setPlatformType(other.getPlatformType());
        }
        if (other.getCoverType() != 0) {
          setCoverType(other.getCoverType());
        }
        if (!other.getCoverResourceList().isEmpty()) {
          coverResourceList_ = other.coverResourceList_;
          onChanged();
        }
        if (!other.getDetailResourceList().isEmpty()) {
          detailResourceList_ = other.detailResourceList_;
          onChanged();
        }
        if (!other.getDetailResourceIdArr().isEmpty()) {
          detailResourceIdArr_ = other.detailResourceIdArr_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BizEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BizEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0L;
        onChanged();
        return this;
      }

      private Object date_ = "";
      /**
       * <code>string date = 2;</code>
       */
      public String getDate() {
        Object ref = date_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string date = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 2;</code>
       */
      public Builder setDate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 2;</code>
       */
      public Builder clearDate() {

        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>string date = 2;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        date_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private Object title_ = "";
      /**
       * <code>string title = 4;</code>
       */
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string title = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 4;</code>
       */
      public Builder setTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 4;</code>
       */
      public Builder clearTitle() {

        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 4;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        title_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 5;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 5;</code>
       */
      public Builder setType(int value) {

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 5;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }

      private Object team_ = "";
      /**
       * <code>string team = 6;</code>
       */
      public String getTeam() {
        Object ref = team_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          team_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string team = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTeamBytes() {
        Object ref = team_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          team_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string team = 6;</code>
       */
      public Builder setTeam(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        team_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string team = 6;</code>
       */
      public Builder clearTeam() {

        team_ = getDefaultInstance().getTeam();
        onChanged();
        return this;
      }
      /**
       * <code>string team = 6;</code>
       */
      public Builder setTeamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        team_ = value;
        onChanged();
        return this;
      }

      private Object imageObj_ = "";
      /**
       * <code>string imageObj = 7;</code>
       */
      public String getImageObj() {
        Object ref = imageObj_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          imageObj_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string imageObj = 7;</code>
       */
      public com.google.protobuf.ByteString
          getImageObjBytes() {
        Object ref = imageObj_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          imageObj_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imageObj = 7;</code>
       */
      public Builder setImageObj(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        imageObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imageObj = 7;</code>
       */
      public Builder clearImageObj() {

        imageObj_ = getDefaultInstance().getImageObj();
        onChanged();
        return this;
      }
      /**
       * <code>string imageObj = 7;</code>
       */
      public Builder setImageObjBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        imageObj_ = value;
        onChanged();
        return this;
      }

      private Object coverObj_ = "";
      /**
       * <code>string coverObj = 8;</code>
       */
      public String getCoverObj() {
        Object ref = coverObj_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          coverObj_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string coverObj = 8;</code>
       */
      public com.google.protobuf.ByteString
          getCoverObjBytes() {
        Object ref = coverObj_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          coverObj_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string coverObj = 8;</code>
       */
      public Builder setCoverObj(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        coverObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string coverObj = 8;</code>
       */
      public Builder clearCoverObj() {

        coverObj_ = getDefaultInstance().getCoverObj();
        onChanged();
        return this;
      }
      /**
       * <code>string coverObj = 8;</code>
       */
      public Builder setCoverObjBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        coverObj_ = value;
        onChanged();
        return this;
      }

      private int direction_ ;
      /**
       * <code>int32 direction = 9;</code>
       */
      public int getDirection() {
        return direction_;
      }
      /**
       * <code>int32 direction = 9;</code>
       */
      public Builder setDirection(int value) {

        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 direction = 9;</code>
       */
      public Builder clearDirection() {

        direction_ = 0;
        onChanged();
        return this;
      }

      private Object description_ = "";
      /**
       * <code>string description = 10;</code>
       */
      public String getDescription() {
        Object ref = description_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string description = 10;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 10;</code>
       */
      public Builder setDescription(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 10;</code>
       */
      public Builder clearDescription() {

        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 10;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        description_ = value;
        onChanged();
        return this;
      }

      private int sequence_ ;
      /**
       * <code>int32 sequence = 11;</code>
       */
      public int getSequence() {
        return sequence_;
      }
      /**
       * <code>int32 sequence = 11;</code>
       */
      public Builder setSequence(int value) {

        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sequence = 11;</code>
       */
      public Builder clearSequence() {

        sequence_ = 0;
        onChanged();
        return this;
      }

      private int category_ ;
      /**
       * <code>int32 category = 12;</code>
       */
      public int getCategory() {
        return category_;
      }
      /**
       * <code>int32 category = 12;</code>
       */
      public Builder setCategory(int value) {

        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 category = 12;</code>
       */
      public Builder clearCategory() {

        category_ = 0;
        onChanged();
        return this;
      }

      private Object authorInfo_ = "";
      /**
       * <code>string authorInfo = 13;</code>
       */
      public String getAuthorInfo() {
        Object ref = authorInfo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          authorInfo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string authorInfo = 13;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorInfoBytes() {
        Object ref = authorInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          authorInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string authorInfo = 13;</code>
       */
      public Builder setAuthorInfo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        authorInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string authorInfo = 13;</code>
       */
      public Builder clearAuthorInfo() {

        authorInfo_ = getDefaultInstance().getAuthorInfo();
        onChanged();
        return this;
      }
      /**
       * <code>string authorInfo = 13;</code>
       */
      public Builder setAuthorInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        authorInfo_ = value;
        onChanged();
        return this;
      }

      private Object url_ = "";
      /**
       * <code>string url = 14;</code>
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string url = 14;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 14;</code>
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 14;</code>
       */
      public Builder clearUrl() {

        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 14;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        url_ = value;
        onChanged();
        return this;
      }

      private int listStatus_ ;
      /**
       * <code>int32 listStatus = 15;</code>
       */
      public int getListStatus() {
        return listStatus_;
      }
      /**
       * <code>int32 listStatus = 15;</code>
       */
      public Builder setListStatus(int value) {

        listStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 listStatus = 15;</code>
       */
      public Builder clearListStatus() {

        listStatus_ = 0;
        onChanged();
        return this;
      }

      private int instSearchStatus_ ;
      /**
       * <code>int32 instSearchStatus = 16;</code>
       */
      public int getInstSearchStatus() {
        return instSearchStatus_;
      }
      /**
       * <code>int32 instSearchStatus = 16;</code>
       */
      public Builder setInstSearchStatus(int value) {

        instSearchStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 instSearchStatus = 16;</code>
       */
      public Builder clearInstSearchStatus() {

        instSearchStatus_ = 0;
        onChanged();
        return this;
      }

      private long instId_ ;
      /**
       * <code>int64 instId = 17;</code>
       */
      public long getInstId() {
        return instId_;
      }
      /**
       * <code>int64 instId = 17;</code>
       */
      public Builder setInstId(long value) {

        instId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 instId = 17;</code>
       */
      public Builder clearInstId() {

        instId_ = 0L;
        onChanged();
        return this;
      }

      private int hasAndroid_ ;
      /**
       * <code>int32 hasAndroid = 18;</code>
       */
      public int getHasAndroid() {
        return hasAndroid_;
      }
      /**
       * <code>int32 hasAndroid = 18;</code>
       */
      public Builder setHasAndroid(int value) {

        hasAndroid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hasAndroid = 18;</code>
       */
      public Builder clearHasAndroid() {

        hasAndroid_ = 0;
        onChanged();
        return this;
      }

      private int hasIOS_ ;
      /**
       * <code>int32 hasIOS = 19;</code>
       */
      public int getHasIOS() {
        return hasIOS_;
      }
      /**
       * <code>int32 hasIOS = 19;</code>
       */
      public Builder setHasIOS(int value) {

        hasIOS_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hasIOS = 19;</code>
       */
      public Builder clearHasIOS() {

        hasIOS_ = 0;
        onChanged();
        return this;
      }

      private Object androidVersion_ = "";
      /**
       * <code>string androidVersion = 20;</code>
       */
      public String getAndroidVersion() {
        Object ref = androidVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          androidVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string androidVersion = 20;</code>
       */
      public com.google.protobuf.ByteString
          getAndroidVersionBytes() {
        Object ref = androidVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          androidVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string androidVersion = 20;</code>
       */
      public Builder setAndroidVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        androidVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string androidVersion = 20;</code>
       */
      public Builder clearAndroidVersion() {

        androidVersion_ = getDefaultInstance().getAndroidVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string androidVersion = 20;</code>
       */
      public Builder setAndroidVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        androidVersion_ = value;
        onChanged();
        return this;
      }

      private Object iosVersion_ = "";
      /**
       * <code>string iosVersion = 21;</code>
       */
      public String getIosVersion() {
        Object ref = iosVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          iosVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string iosVersion = 21;</code>
       */
      public com.google.protobuf.ByteString
          getIosVersionBytes() {
        Object ref = iosVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          iosVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string iosVersion = 21;</code>
       */
      public Builder setIosVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        iosVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string iosVersion = 21;</code>
       */
      public Builder clearIosVersion() {

        iosVersion_ = getDefaultInstance().getIosVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string iosVersion = 21;</code>
       */
      public Builder setIosVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        iosVersion_ = value;
        onChanged();
        return this;
      }

      private int platformType_ ;
      /**
       * <code>int32 platformType = 22;</code>
       */
      public int getPlatformType() {
        return platformType_;
      }
      /**
       * <code>int32 platformType = 22;</code>
       */
      public Builder setPlatformType(int value) {

        platformType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 platformType = 22;</code>
       */
      public Builder clearPlatformType() {

        platformType_ = 0;
        onChanged();
        return this;
      }

      private int coverType_ ;
      /**
       * <code>int32 coverType = 23;</code>
       */
      public int getCoverType() {
        return coverType_;
      }
      /**
       * <code>int32 coverType = 23;</code>
       */
      public Builder setCoverType(int value) {

        coverType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 coverType = 23;</code>
       */
      public Builder clearCoverType() {

        coverType_ = 0;
        onChanged();
        return this;
      }

      private Object coverResourceList_ = "";
      /**
       * <code>string coverResourceList = 24;</code>
       */
      public String getCoverResourceList() {
        Object ref = coverResourceList_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          coverResourceList_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string coverResourceList = 24;</code>
       */
      public com.google.protobuf.ByteString
          getCoverResourceListBytes() {
        Object ref = coverResourceList_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          coverResourceList_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string coverResourceList = 24;</code>
       */
      public Builder setCoverResourceList(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        coverResourceList_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string coverResourceList = 24;</code>
       */
      public Builder clearCoverResourceList() {

        coverResourceList_ = getDefaultInstance().getCoverResourceList();
        onChanged();
        return this;
      }
      /**
       * <code>string coverResourceList = 24;</code>
       */
      public Builder setCoverResourceListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        coverResourceList_ = value;
        onChanged();
        return this;
      }

      private Object detailResourceList_ = "";
      /**
       * <code>string detailResourceList = 25;</code>
       */
      public String getDetailResourceList() {
        Object ref = detailResourceList_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          detailResourceList_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string detailResourceList = 25;</code>
       */
      public com.google.protobuf.ByteString
          getDetailResourceListBytes() {
        Object ref = detailResourceList_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          detailResourceList_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string detailResourceList = 25;</code>
       */
      public Builder setDetailResourceList(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        detailResourceList_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string detailResourceList = 25;</code>
       */
      public Builder clearDetailResourceList() {

        detailResourceList_ = getDefaultInstance().getDetailResourceList();
        onChanged();
        return this;
      }
      /**
       * <code>string detailResourceList = 25;</code>
       */
      public Builder setDetailResourceListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        detailResourceList_ = value;
        onChanged();
        return this;
      }

      private Object detailResourceIdArr_ = "";
      /**
       * <code>string detailResourceIdArr = 26;</code>
       */
      public String getDetailResourceIdArr() {
        Object ref = detailResourceIdArr_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          detailResourceIdArr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string detailResourceIdArr = 26;</code>
       */
      public com.google.protobuf.ByteString
          getDetailResourceIdArrBytes() {
        Object ref = detailResourceIdArr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          detailResourceIdArr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string detailResourceIdArr = 26;</code>
       */
      public Builder setDetailResourceIdArr(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        detailResourceIdArr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string detailResourceIdArr = 26;</code>
       */
      public Builder clearDetailResourceIdArr() {

        detailResourceIdArr_ = getDefaultInstance().getDetailResourceIdArr();
        onChanged();
        return this;
      }
      /**
       * <code>string detailResourceIdArr = 26;</code>
       */
      public Builder setDetailResourceIdArrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        detailResourceIdArr_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.java.core.redis.protobuf.BizEvent)
    }

    // @@protoc_insertion_point(class_scope:com.java.core.redis.protobuf.BizEvent)
    private static final BizEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BizEvent();
    }

    public static BizEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BizEvent>
        PARSER = new com.google.protobuf.AbstractParser<BizEvent>() {
      @Override
      public BizEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BizEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BizEvent> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BizEvent> getParserForType() {
      return PARSER;
    }

    @Override
    public BizEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_core_redis_protobuf_BizEvent_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_core_redis_protobuf_BizEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024BizEventProtoc.proto\022\034com.java.core.re" +
      "dis.protobuf\"\371\003\n\010BizEvent\022\n\n\002id\030\001 \001(\003\022\014\n" +
      "\004date\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\r\n\005title\030\004 \001(\t" +
      "\022\014\n\004type\030\005 \001(\005\022\014\n\004team\030\006 \001(\t\022\020\n\010imageObj" +
      "\030\007 \001(\t\022\020\n\010coverObj\030\010 \001(\t\022\021\n\tdirection\030\t " +
      "\001(\005\022\023\n\013description\030\n \001(\t\022\020\n\010sequence\030\013 \001" +
      "(\005\022\020\n\010category\030\014 \001(\005\022\022\n\nauthorInfo\030\r \001(\t" +
      "\022\013\n\003url\030\016 \001(\t\022\022\n\nlistStatus\030\017 \001(\005\022\030\n\020ins" +
      "tSearchStatus\030\020 \001(\005\022\016\n\006instId\030\021 \001(\003\022\022\n\nh" +
      "asAndroid\030\022 \001(\005\022\016\n\006hasIOS\030\023 \001(\005\022\026\n\016andro" +
      "idVersion\030\024 \001(\t\022\022\n\niosVersion\030\025 \001(\t\022\024\n\014p" +
      "latformType\030\026 \001(\005\022\021\n\tcoverType\030\027 \001(\005\022\031\n\021" +
      "coverResourceList\030\030 \001(\t\022\032\n\022detailResourc" +
      "eList\030\031 \001(\t\022\033\n\023detailResourceIdArr\030\032 \001(\t" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_java_core_redis_protobuf_BizEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_java_core_redis_protobuf_BizEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_core_redis_protobuf_BizEvent_descriptor,
        new String[] { "Id", "Date", "Name", "Title", "Type", "Team", "ImageObj", "CoverObj", "Direction", "Description", "Sequence", "Category", "AuthorInfo", "Url", "ListStatus", "InstSearchStatus", "InstId", "HasAndroid", "HasIOS", "AndroidVersion", "IosVersion", "PlatformType", "CoverType", "CoverResourceList", "DetailResourceList", "DetailResourceIdArr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
